version: '3.9'

services:
  web:
    build: .
    command: gunicorn bookstore_gateway.bookstore_gateway.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=bookstore_gateway.bookstore_gateway.settings
    ports:
      - "8000:8000"
    env_file:
      - .env
