version: '3.9'

services:
  api-gateway:
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    command: gunicorn bookstore_gateway.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./api-gateway:/app
    environment:
      - DJANGO_SETTINGS_MODULE=bookstore_gateway.settings
    ports:
      - "8000:8000"
    env_file:
      - ./api-gateway/.env
  
  review-service:
    build: 
      context: ./review_service
      dockerfile: Dockerfile
    command: gunicorn review_service.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - ./review_service:/app
    ports:
      - "8001:8001"
    env_file:
      - ./review_service/.env
