version: '3.9'

services:
  api-gateway:
    build: 
      context: .
      dockerfile: Dockerfile_api_gateway
    command: gunicorn bookstore_gateway.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=bookstore_gateway.settings
    ports:
      - "8000:8000"
    env_file:
      - .env
